-- return {
--   "jay-babu/mason-nvim-dap.nvim",
--   dependencies = "mason.nvim",
--   cmd = { "DapInstall", "DapUninstall" },
--   opts = {
--     -- Makes a best effort to setup the various debuggers with
--     -- reasonable debug configurations
--     automatic_installation = true,
--
--     -- You can provide additional configuration to the handlers,
--     -- see mason-nvim-dap README for more information
--     handlers = {
--       python = function(config)
--         config.adapters = {
--           type = "executable",
--           command = "/usr/bin/python3",
--           args = {
--             "-m",
--             "debugpy.adapter",
--           },
--         }
--         require("mason-nvim-dap").default_setup(config) -- don't forget this!
--       end,
--     },
--
--     -- You'll need to check that you have the required things installed
--     -- online, please don't ask me how to install them :)
--     ensure_installed = {
--       -- Update this to ensure that you have the debuggers for the langs you want
--       "python",
--       "delve",
--       "js",
--       "go",
--       "codelldb",
--       "bash",
--     },
--   },
--   -- mason-nvim-dap is loaded when nvim-dap loads
--   config = function()
--     require("mason-nvim-dap").setup({})
--   end,
-- }
return {}
